import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/app/components/providers/ThemeProvider";
import { PageTransitionProvider } from "./components/providers/PageTransitionProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <PageTransitionProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </PageTransitionProvider>
      </body>
    </html>
  );
}
